spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}?currentSchema=${DATABASE_SCHEMA:cameraevents}"
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
kafka:
  bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
  consumer:
    group-id: ${GROUP_ID:test-consumer-group}
  topic-name: ${TOPIC_NAME:SpeedControl}
server:
  port: 42099
internal:
  camera:
    speed-limit: ${SPEED_LIMIT:80}

application-description: camera-service
application-version: 1.0.0
#springdoc:
#  api-docs:
#    path: swagger
